services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo2:
    image: mongo:latest
    container_name: mongo2
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo-setup:
    image: mongo:latest
    depends_on:
      - mongo1
      - mongo2
    entrypoint: >
      bash -c "
      sleep 5;
      echo 'rs.initiate({
        _id: \"rs0\",
        members: [
          { _id: 0, host: \"mongo1:27017\", priority: 1 },
          { _id: 1, host: \"mongo2:27017\", priority: 0.5 }
        ]
      })' | mongo --host mongo1:27017
      "
